"""Added Password Field

Revision ID: 68390a6bdd65
Revises: be9ab64cdb30
Create Date: 2023-04-25 10:39:50.343753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68390a6bdd65'
down_revision = 'be9ab64cdb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
